# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Indelible Labs
            image:
        nav:
            - item_name: Item 1
              item_url: '#'
            - item_name: Item 2
              item_url: '#'
            - item_name: Item 3
              item_url: '#'
    footer:
        content:
            logo:
                text: Indelible Labs
                image:
            copyright: Copyright &copy; 2022. - Indelible Labs LLC <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/indelible_labs'
            - network_name: discord
              profile_url: 'https://discord.gg/indelible'
    google_analytics:
        tracking_code: G-G0GEB06J1G
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
