# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Indelible Labs
            image: /theme/assets/images/layout/logo.svg
    footer:
        content:
            logo:
                text: Indelible Labs
            copyright: Copyright &copy; 2023 - Indelible Labs LLC<br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/indelible_labs'
            - network_name: discord
              profile_url: 'https://discord.gg/indelible'
    google_analytics:
        tracking_code: G-G0GEB06J1G
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./theme/_layouts
includes_dir: ./theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
